# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: featureengineering.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='featureengineering.proto',
  package='featureengineering',
  syntax='proto3',
  serialized_options=b'\n#io.grpc.examples.featureengineeringB\024FeatureEngineerProtoP\001\242\002\003FEG',
  serialized_pb=b'\n\x18\x66\x65\x61tureengineering.proto\x12\x12\x66\x65\x61tureengineering\"E\n\x05\x45vent\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\n\n\x02\x66\x31\x18\x02 \x01(\x05\x12\n\n\x02\x66\x32\x18\x03 \x01(\x05\x12\n\n\x02\x66\x33\x18\x04 \x01(\x05\x12\n\n\x02\x66\x34\x18\x05 \x01(\x05\"5\n\tEventList\x12(\n\x05\x65vent\x18\x01 \x03(\x0b\x32\x19.featureengineering.Event\"q\n\x07\x46\x45\x45vent\x12\x37\n\x06result\x18\x01 \x03(\x0b\x32\'.featureengineering.FEEvent.ResultEntry\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\x63\n\x0f\x46\x65\x61tureEngineer\x12P\n\x10\x65ngineerFeatures\x12\x1d.featureengineering.EventList\x1a\x1b.featureengineering.FEEvent\"\x00\x42\x43\n#io.grpc.examples.featureengineeringB\x14\x46\x65\x61tureEngineerProtoP\x01\xa2\x02\x03\x46\x45Gb\x06proto3'
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='featureengineering.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='featureengineering.Event.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f1', full_name='featureengineering.Event.f1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f2', full_name='featureengineering.Event.f2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f3', full_name='featureengineering.Event.f3', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f4', full_name='featureengineering.Event.f4', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=117,
)


_EVENTLIST = _descriptor.Descriptor(
  name='EventList',
  full_name='featureengineering.EventList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='featureengineering.EventList.event', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=172,
)


_FEEVENT_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='featureengineering.FEEvent.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='featureengineering.FEEvent.ResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='featureengineering.FEEvent.ResultEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=287,
)

_FEEVENT = _descriptor.Descriptor(
  name='FEEvent',
  full_name='featureengineering.FEEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='featureengineering.FEEvent.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FEEVENT_RESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=287,
)

_EVENTLIST.fields_by_name['event'].message_type = _EVENT
_FEEVENT_RESULTENTRY.containing_type = _FEEVENT
_FEEVENT.fields_by_name['result'].message_type = _FEEVENT_RESULTENTRY
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['EventList'] = _EVENTLIST
DESCRIPTOR.message_types_by_name['FEEvent'] = _FEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'featureengineering_pb2'
  # @@protoc_insertion_point(class_scope:featureengineering.Event)
  })
_sym_db.RegisterMessage(Event)

EventList = _reflection.GeneratedProtocolMessageType('EventList', (_message.Message,), {
  'DESCRIPTOR' : _EVENTLIST,
  '__module__' : 'featureengineering_pb2'
  # @@protoc_insertion_point(class_scope:featureengineering.EventList)
  })
_sym_db.RegisterMessage(EventList)

FEEvent = _reflection.GeneratedProtocolMessageType('FEEvent', (_message.Message,), {

  'ResultEntry' : _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _FEEVENT_RESULTENTRY,
    '__module__' : 'featureengineering_pb2'
    # @@protoc_insertion_point(class_scope:featureengineering.FEEvent.ResultEntry)
    })
  ,
  'DESCRIPTOR' : _FEEVENT,
  '__module__' : 'featureengineering_pb2'
  # @@protoc_insertion_point(class_scope:featureengineering.FEEvent)
  })
_sym_db.RegisterMessage(FEEvent)
_sym_db.RegisterMessage(FEEvent.ResultEntry)


DESCRIPTOR._options = None
_FEEVENT_RESULTENTRY._options = None

_FEATUREENGINEER = _descriptor.ServiceDescriptor(
  name='FeatureEngineer',
  full_name='featureengineering.FeatureEngineer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=289,
  serialized_end=388,
  methods=[
  _descriptor.MethodDescriptor(
    name='engineerFeatures',
    full_name='featureengineering.FeatureEngineer.engineerFeatures',
    index=0,
    containing_service=None,
    input_type=_EVENTLIST,
    output_type=_FEEVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEATUREENGINEER)

DESCRIPTOR.services_by_name['FeatureEngineer'] = _FEATUREENGINEER

# @@protoc_insertion_point(module_scope)
